name: twitter_sign_in_example
description: Demonstrates how to use the twitter_sign_in plugin.
publish_to: "none"

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  twitter_sign_in:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/twitter_dashboard.png
