name: twitter_sign_in
description: A Flutter plugin for signing in with Twitter.

version: 5.0.1

homepage: https://github.com/jayfinava-benzatine/twitter_sign_in
repository: https://github.com/jayfinava-benzatine/twitter_sign_in

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.maru.twitter_login
        pluginClass: TwitterLoginPlugin
      ios:
        pluginClass: TwitterLoginPlugin
      macos:
        pluginClass: TwitterLoginPlugin
